export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const RESIZE_SCREEN = 'RESIZE_SCREEN'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const REGISTER_USER_MODAL = 'REGISTER_USER_MODAL'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const USER_FETCH = 'USER_FETCH'
export const USER_INFO = 'USER_INFO'

export const USERS_FETCH = 'USERS_FETCH'
export const USERS_INFO = 'USERS_INFO'

export const AVATAR_MENU = 'AVATAR_MENU'
export const AVATAR_MENU_IS_SHOWING = 'AVATAR_MENU_IS_SHOWING'
